### PR TITLE
Use AST for markup generation instead of side-effects in ETS.

### PR DESCRIPTION
**Pull request by romul**
Hi Steve,
I thought about how Xain works and I came to the conclusion that use of ets is not required.
Please, take a look at implementation based on simple manipulations with AST. It converts body of `do` block to something like:

``` elixir
xain_buffer = []
xain_buffer = [line1 | xain_buffer]
xain_buffer = [line2 | xain_buffer]
Xain.join(xain_buffer)
```

The implementation is API-compatible, i.e. all tests are passed without any change.
Although there is one change: you couldn't use function with side-effects to produce html anymore. 
For example:

``` elixir
markup do
  div("1")
  div("2")
  div("3")
end
# => "<div>1</div><div>2</div><div>3</div>"

# but
try_to_do_side_effects = fn -> 
  div("1")
  div("2")
  div("3")
end
try_to_do_side_effects.() # => "<div>3</div>"
```

Thereby this change will require some refactoring in ex_admin to ditch side-effects. But I think this would be a very good changes and will improve readability and perspicuity of the code, b/c functional programming is hardly compatible with such the side-effects and encourage pure functions. So watching how a call of some function without any handling of its result produce some HTML in other place is kind of WAT.

### CODE REVIEW

**Comment by smpallen99** [comment]
I really like the idea. Agree, eliminating side affects is a good thing. I want to play around with it and try a few things...

**Comment by smpallen99** [comment]
so far so good. I created a few additional tests to check different scenarios and they all work. Also, looks like we don't need the `markup :nested do` anymore. Thats cool. I sleep on it and might try some more testing tomorrow.

``` elixir
  test "supports nested markups without :nested" do
    result = markup do
      div "one"
      div "two"
      markup do
        div "three"
      end
    end
    assert result == ~s(<div>one</div><div>two</div><div>three</div>)
  end

  test "support inline code" do
    result = markup do
      div "one"
      val = "something"
      div val
    end
    assert result == ~s(<div>one</div><div>something</div>)
  end

  test "support markup generated in functions" do
    fun = fn ->
      markup do
        div "my-fun"
      end
    end
    result = markup do
      div do
        text "first"
        fun.()
      end
    end
    assert result == ~s(<div>first<div>my-fun</div></div>)
  end
```

**Comment by romul** [comment]
> Also, looks like we don't need the markup :nested do anymore.

Yeah, I didn't remove it to keep backward compatible. But it should be one function with optional unused argument instead of two in any case :-)

**Comment by romul** [comment]
@smpallen99 
Btw, `markup` is now just a way to combine several tags without wrapping them in `div`. Therefore it could be used to eliminate side-effects in functions. Besides, you could return a list of tags from a function, it will work in nested cases too.

``` elixir
# bad (b/c relies on side effects)
try_to_do_side_effects = fn -> 
  div("1")
  div("2")
  div("3")
end
# function returns result of the last expression as expected
try_to_do_side_effects.() 
# => "<div>3</div>"

# good
generate_several_tags_with_markup = fn -> 
  markup do
    div("1")
    div("2")
    div("3")
  end
end
generate_several_tags_with_markup.()  
# => "<div>1</div><div>2</div><div>3</div>"

# good
generate_several_tags_with_list = fn -> 
  [
    div("1"),
    div("2"),
    div("3"),
  ]
end

div id: "main" do
  generate_several_tags_with_list.() 
end 
# => "<div id=\"main\"><div>1</div><div>2</div><div>3</div></div>"
```

**Pull request merged**
